name: estore_app
description: Juwei Store Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+210424

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  community_material_icon: ^5.8.55
  permission_handler: ^5.1.0+2
#  permission_handler_platform_interface: ^2.0.1
  app_settings: ^4.0.4
  http: ^0.12.2
  image: ^2.1.19
  flutter_spinkit: ^4.1.2+1
  getwidget: ^1.2.2
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  equatable: ^1.2.6
  device_info: ^1.0.0
  package_info: ^0.4.3+4
  ansicolor: ^1.1.1
  path_provider: ^1.6.27
  get_ip: ^0.4.0
  sqflite: ^1.3.2+4
  r_upgrade: ^0.3.2+3
  back_button_interceptor: ^4.4.2
  flutter_conditional_rendering: ^1.1.1
  flutter_easyloading: ^2.2.2
  oktoast: ^2.3.2
  quiver: ^2.1.5
  dio: ^3.0.10
  flutter_keyboard_visibility: ^4.0.3
  flutter_custom_dialog: ^1.0.20
  fluro: ^1.7.8
  cached_network_image: ^2.3.3
  flutter_bcrypt: ^1.0.5
  sprintf: ^5.0.0
  rational: ^0.3.8
  barcode_scan: ^3.0.1
  get: ^3.15.0
  mqtt_client: ^8.0.0
  jiffy: ^3.0.1
  xml_parser: ^0.1.2
  qr_flutter: ^3.2.0
  barcode: ^1.17.1
  barcode_image: ^1.2.0
  gbk_codec: ^0.3.2
  dart_extensions: ^1.0.2
  flutter_tts: ^1.3.0
  encrypt: ^4.1.0
  keyboard_avoider: ^0.1.2
  connectivity: ^2.0.1
  flutter_easyrefresh: ^2.1.6
  charcode: ^1.1.3
  system_info: ^0.1.3
  retry: ^3.0.1
  dart_notification_center: ^1.0.0+1
  flutter_beautiful_popup: ^1.5.0
  expandable: ^4.1.4
  string_unescape: ^1.5.1
  auto_size_text: ^2.1.0
  auto_size_text_field: ^0.1.7
  flui: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/js/
    - assets/fonts/
    - assets/images/
    - assets/images/download/
    - assets/images/login/
    - assets/images/home/
    - assets/template/
    - assets/template/printer/

  fonts:
    - family: Alibaba PuHuiTi
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Regular.otf
        - asset: assets/fonts/Alibaba-PuHuiTi-Light.otf
          weight: 400
        - asset: assets/fonts/Alibaba-PuHuiTi-Medium.otf
          weight: 600
        - asset: assets/fonts/Alibaba-PuHuiTi-Bold.otf
          weight: 700
        - asset: assets/fonts/Alibaba-PuHuiTi-Heavy.otf
          weight: 800
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf